### PR TITLE
feat(tutorial): complete step 4

### PR DESCRIPTION
**Pull request by superman566**

### CODE REVIEW

**Comment by lee-chase** [comment]
@superman566 :cold_sweat: something doesn't look right. Take a look at the accessibility section.

**Comment by superman566** [comment]
Hi @lee-chase , I installed the Dynamic Assessment Plugin(1.8.0.0), I only can see one violation for  the off-screen “skip to content” link. Do I need ignore it, right?
image

**Comment by superman566** [comment]
do I still need to fix Potential Violations?

**Comment by lee-chase** [comment]
> do I still need to fix Potential Violations?

My apologies, my DAP tool was out of date.

**Pull request closed without merging**
