### PR TITLE
feat(tutorial): complete step 5

### PR DESCRIPTION
**Pull request by jerbeemacalino**

### CODE REVIEW

**Comment by lee-chase** [comment]
Please post a link to your IBM cloud deployment if you can

**Comment by jerbeemacalino** [comment]
> Please post a link to your IBM cloud deployment if you can

https://carbon-tutorial-vue-jerbeemacalino.mybluemix.net/

**Comment by jerbeemacalino** [comment]
hi, cant deployed the project on the IBM cloud, I deployed the tutorial on my host. Please check this link - https://jerbeemacalino.000webhostapp.com/#/

**Comment by jerbeemacalino** [comment]
> Please post a link to your IBM cloud deployment if you can

https://jerbeemacalino.000webhostapp.com/#/

**Comment by lee-chase** [comment]
@jerbeemacalino you appear to have some styling issues in both the deployed version of the app. This may well be due to the removal of the grid feature flag.

**Comment by jerbeemacalino** [comment]
> @jerbeemacalino you appear to have some styling issues in both the deployed version of the app. This may well be due to the removal of the grid feature flag.

@lee-chase made some fixed now can you please check both https://jerbeemacalino.000webhostapp.com/#/ and deployed version now.

**Comment by lee-chase** [comment]
:thumbsup::100::clap::smile::star:fantastic, you have completed the tutorial and if you have completed all five steps you can now take a look at the wrapping up step where you will find instructions on claiming the Carbon Developer Essentials Vue badge. Feel free to stop your running application on IBM Cloud to avoid the possibility of incurring any charges.

**Pull request closed without merging**
