### PR TITLE
feat(tutorial): complete step 5

### PR DESCRIPTION
**Pull request by peakrock**

### CODE REVIEW

**Comment by ibmer20** [comment]
You accidentally removed an extra line in the scss file regarding carbon-fixes.  Fix that and push again, as well as make sure your cloud website is working

**Comment by peakrock** [comment]
@Pablodotnet  I have fixed this issue, please help to review the code again, thanks.

**Comment by peakrock** [comment]
@ibmer20 I have fixed this issue, please help to review the code again, thanks.

**Comment by ibmer20** [comment]
@peakrock The issue is not resolved.

**Comment by peakrock** [comment]
@ibmer20  Thanks for your reminder, I fix the code issue. please help review the code again.

**Comment by peakrock** [comment]
@ibmer20 hello, pls help review, thanks.

**Comment by ibmer20** [comment]
@peakrock You did not push the latest code to IBM Cloud

**Comment by peakrock** [comment]
> @peakrock You did not push the latest code to IBM Cloud
I have redeploy the package to IBM Cloud. you can check it. thx.
https://carbon-tutorial-vue-peakrock.mybluemix.net

**Comment by ibmer20** [comment]
👍💯👏😄⭐️fantastic, you have completed the tutorial and can now claim the Carbon Developer Essentials Vue badge.  Go complete the wrapping up step https://www.carbondesignsystem.com/tutorial/vue/wrapping-up to get credit for the badge.

Feel free to stop your running application on IBM Cloud to avoid the possibility of incurring any charges.

**Pull request closed without merging**
