### PR TITLE
feat(tutorial): complete step 5

### PR DESCRIPTION
**Pull request by ricardoaugusto**
https://carbon-tutorial-vue-ricardoaugusto.mybluemix.net/#/

### CODE REVIEW

**Comment by lee-chase** [comment]
:cold_sweat: something doesn't look right. Can you post a link to your ibm cloud deployed page.

**Comment by ricardoaugusto** [comment]
https://carbon-tutorial-vue-ricardoaugusto.mybluemix.net/#/

**Comment by ricardoaugusto** [comment]
@lee-chase @Pablodotnet yay I think I've managed to push to the IBM Cloud

**Comment by lee-chase** [comment]
:thumbsup::100::clap::smile::star:fantastic, you have completed the tutorial and if you have completed all five steps you can now claim the Carbon Developer Essentials Vue badge.  Feel free to stop your running application on IBM Cloud to avoid the possibility of incurring any charges.

**Pull request closed without merging**
