### PR TITLE
feat(tutorial): complete step 5 - Boeblingen

### PR DESCRIPTION
**Pull request by janhassel**
https://carbon-tutorial-vue-janhassel.eu-gb.mybluemix.net/

### CODE REVIEW

**Comment by ZrianinaMariia** [comment]
:cold_sweat: something doesn't look right. Take a look at the Repo page on IBM cloud.

**Comment by janhassel** [comment]
Ah sorry, still had my local dev proxy in the `.env.local`. Deployed a fix.

**Comment by ZrianinaMariia** [comment]
thumbsup::100::clap::smile::star:fantastic, you have completed the tutorial and can now claim the Carbon Developer Essentials Vue badge.

**Comment by ZrianinaMariia** [comment]
Feel free to stop your running application on IBM Cloud to avoid the possibility of incurring any charges.

**Pull request closed without merging**
