### PR TITLE
feat(tutorial): complete step 4

### PR DESCRIPTION
**Pull request by nicoeinsidler**

### CODE REVIEW

**Comment by lee-chase** [comment]
You appear to be missing some items from your cards

**Comment by nicoeinsidler** [comment]
> You appear to be missing some items from your cards

What do you mean by "your cards"?

**Comment by nicoeinsidler** [comment]
I hope that my code meets all requirements now. :)

**Comment by lee-chase** [comment]
:thumbsup: looks good, you are one step closer to earning the Carbon Developer Essentials Vue badge

**Pull request closed without merging**
