### PR TITLE
feat(tutorial): complete step 5

### PR DESCRIPTION
**Pull request by Undid-Iridium**

### CODE REVIEW

**Comment by Undid-Iridium** [comment]
http://carbon-tutorial-vue-undid-iridium.mybluemix.net/#/

**Comment by Undid-Iridium** [comment]
Unsure what is wrong. It loads locally, I am not sure what could be causing it to not load on the online side.

**Comment by Undid-Iridium** [comment]
Nevermind, it was a bad link (Being HTTP screwed it up it seems). https://carbon-tutorial-vue-undid-iridium.mybluemix.net/#/repos

**Comment by Pablodotnet** [comment]
:thumbsup::100::clap::smile::star:fantastic, you have completed the tutorial and can now claim the Carbon Developer Essentials Vue badge.  Feel free to stop your running application on IBM Cloud to avoid the possibility of incurring any charges.

**Pull request closed without merging**
