### PR TITLE
feat(tutorial): complete step 5

### PR DESCRIPTION
**Pull request by superman566**

### CODE REVIEW

**Comment by lee-chase** [comment]
:cold_sweat: something doesn't look right. The carbon-fixes scss import needs adding back. Plus could you add a link to your bluemix deployment.

**Comment by superman566** [comment]
https://carbon-tutorial-vue-superman566.mybluemix.net/#/

**Comment by superman566** [comment]
@lee-chase can you take a look at the new change?

**Comment by superman566** [comment]
@lee-chase I've updated the scss fix and attached the bluemix URL. can you take a look?

**Comment by lee-chase** [comment]
:thumbsup::100::clap::smile::star:fantastic, you have completed the tutorial and if you have completed all five steps you can now take a look at the wrapping up step where you will find instructions on claiming the Carbon Developer Essentials Vue badge. Feel free to stop your running application on IBM Cloud to avoid the possibility of incurring any charges.

**Comment by superman566** [comment]
Thanks Let me know this. i will apply that badge soon

**Pull request closed without merging**
