### PR TITLE
feat(tutorial): complete step 2 - Bangalore

### PR DESCRIPTION
**Pull request by pfarkya**

### CODE REVIEW

**Comment by lee-chase** [comment]
:cold_sweat: something doesn't look right. Take a look at the styling of the tabs and the repositories pages.

**Comment by pfarkya** [comment]
Updated as reviewed

**Comment by lee-chase** [comment]
😰 something doesn't look right. Your data table component seems to be missing a cv-data-table.

**Comment by pfarkya** [comment]
Yup, Sorry missed it. 
Once more done that changes

**Comment by lee-chase** [comment]
:thumbsup: looks good, you are one step closer to earning the Carbon Developer Essentials Vue badge

**Pull request closed without merging**
