### PR TITLE
feat(tutorial): complete step 5

### PR DESCRIPTION
**Pull request by fabqb**
thanks

### CODE REVIEW

**Comment by lee-chase** [comment]
Please post a link to your IBM cloud deployment if you can

**Comment by fabqb** [comment]
Hello Lee, 

here is the link but I have a forbidden page: 

https://carbon-tutorial-vue-fabricedaguet.eu-gb.mybluemix.net/


here is the log. I am not sure what to change to be able to allow the directory: 

2020/09/28 17:05:16 [error] 107#0: *18498 directory index of "/home/vcap/app/public/" is forbidden, client: 10.247.217.117, server: localhost, request: "GET / HTTP/1.1", host: "carbon-tutorial-vue-fabricedaguet.eu-gb.mybluemix.net", referrer: "https://cloud.ibm.com/apps/1408bdde-0be7-400c-884e-6aee343a1c1f?ace_config=%7B%22region%22%3A%22eu-gb%22%2C%22crn%22%3A%22crn%3Av1%3Abluemix%3Apublic%3Acf%3Aeu-gb%3As%2Ffcf454aa-4a40-4858-8fc6-6811300d2167%3A%3Acf-application%3A1408bdde-0be7-400c-884e-6aee343a1c1f%22%2C%22resource_id%22%3A%221408bdde-0be7-400c-884e-6aee343a1c1f%22%2C%22orgGuid%22%3A%22b1101338-402a-4e8c-aa6e-31e959160cf2%22%2C%22spaceGuid%22%3A%22fcf454aa-4a40-4858-8fc6-6811300d2167%22%2C%22redirect%22%3A%22https%3A%2F%2Fcloud.ibm.com%2Fresources%22%2C%22bluemixUIVersion%22%3A%22v6%22%7D&env_id=ibm%3Ayp%3Aeu-gb&paneId=overview"

**Comment by lee-chase** [comment]
@fabqb you appear to be missing Staticfile see https://www.carbondesignsystem.com/developing/vue-tutorial/step-5#create-static-file

**Comment by fabqb** [comment]
ok I finally had time to work on this and could find the location of the pull request. 

It works now.

The link is:  https://carbon-tutorial-vue-fabricedaguet.eu-gb.mybluemix.net/

**Comment by lee-chase** [comment]
:thumbsup::100::clap::smile::star:fantastic, you have completed the tutorial and if you have completed all five steps you can now take a look at the wrapping up step where you will find instructions on claiming the Carbon Developer Essentials Vue badge. Feel free to stop your running application on IBM Cloud to avoid the possibility of incurring any charges.

**Pull request closed without merging**
