### PR TITLE
feat(tutorial): complete step 3

### PR DESCRIPTION
**Pull request by MartyFu2017**

### CODE REVIEW

**Comment by lee-chase** [comment]
:cold_sweat: something doesn't look right. Take a look at the links column in the table.

**Comment by lee-chase** [comment]
:thumbsup: looks good, you are one step closer to earning the Carbon Developer Essentials Vue badge

**Comment by lee-chase** [comment]
Ooops, closed in error sorry.

**Comment by MartyFu2017** [comment]
Thanks for pointing that out. Please check again.

**Comment by lee-chase** [comment]
:thumbsup: looks good, you are one step closer to earning the Carbon Developer Essentials Vue badge

**Pull request closed without merging**
