### PR TITLE
feat(tutorial): complete step 3

### PR DESCRIPTION
**Pull request by pedrohss95**

### CODE REVIEW

**Comment by pedrohss95** [comment]
hey @lee-chase, I didn't understand the error, with the preview for netlifly and checking again I cannot find any error. Could you please help me?

**Comment by lee-chase** [comment]
@mergify refresh

**Comment by lee-chase** [comment]
Hi @pedrohss95, please accept my apologies that you have become the first person to pass through the automated tests.

In this instance, I had left a call to run the format:diff script in the circle-ci configuration. This meant that it was complaining about how some of the code was formatted, this was not intentional.

**Comment by pedrohss95** [comment]
no problem @lee-chase, thanks for the support!!

**Pull request closed without merging**
