### PR TITLE
feat(tutorial): complete step 5

### PR DESCRIPTION
**Pull request by wlwanwl**
deployed site: https://carbon-tutorial-vue-wlwanwl.au-syd.mybluemix.net

### CODE REVIEW

**Comment by wlwanwl** [comment]
deployed site: https://carbon-tutorial-vue-wlwanwl.au-syd.mybluemix.net

**Comment by lee-chase** [comment]
You appear to have removed the import of the carbon-fixes scss file

**Comment by wlwanwl** [comment]
fixed missing carbon-fixes issue

**Comment by lee-chase** [comment]
> @lee-chase, I fixed missing carbon-fixes issue and deployed new code to site, please check, thanks

Unfortunately, the IBM Cloud link above does not work. Please check it is correct.

**Pull request closed without merging**
