### PR TITLE
Vue step 5

### PR DESCRIPTION
**Pull request by PiotrDevCAN**
I've finished a fifth part of tutorial.
Kindly make a review, please

### CODE REVIEW

**Comment by lee-chase** [comment]
Please post a link to your IBM Cloud deployment.

**Comment by PiotrDevCAN** [comment]
During deployment I receive sn error saying the start script is missing. I know it should be in a package.json file however what npm command it should execute ?

**Comment by lee-chase** [comment]
The deploy script you inserted needs moving up to line 12.

**Comment by PiotrDevCAN** [comment]
Please make a review and approve if you won't find any issues

**Comment by lee-chase** [comment]
:thumbsup::100::clap::smile::star:fantastic, you have completed the tutorial and if you have completed all five steps you can now take a look at the wrapping up step where you will find instructions on claiming the Carbon Developer Essentials Vue badge. Feel free to stop your running application on IBM Cloud to avoid the possibility of incurring any charges.

**Pull request closed without merging**
