### PR TITLE
Vue step 4

### PR DESCRIPTION
**Pull request by SauloRomo**

### CODE REVIEW

**Comment by lee-chase** [comment]
:cold_sweat: something doesn't look right. Take a look at the accessibility section.

**Comment by SauloRomo** [comment]
> 😰 something doesn't look right. Take a look at the accessibility section.

@lee-chase  done :)

**Comment by SauloRomo** [comment]
@Pablodotnet Done :)

**Comment by Pablodotnet** [comment]
:thumbsup: looks good, you are one step closer to earning the Carbon Developer Essentials Vue badge

**Pull request closed without merging**
