### PR TITLE
feat(tutorial): complete step 2

### PR DESCRIPTION
**Pull request by koreskos**

### CODE REVIEW

**Comment by lee-chase** [comment]
Somethings not quite right with your deploy. Try pushing a comment or space change to trigger another build.

**Comment by koreskos** [comment]
I have pushed a change per your request

**Comment by koreskos** [comment]
I did not see a new build but when I click on the deploy link above things look ok to me.  What did you see in the deploy that was incorrect?

**Comment by koreskos** [comment]
Hello Lee,

Is everything ok now?

Thanks .. Sonya

Sonya Koresko
External 607 429-3714 Internal: 620-3714
email: koresko@us.ibm.com

**Comment by lee-chase** [comment]
:thumbsup: looks good, you are one step closer to earning the Carbon Developer Essentials Vue badge

**Pull request closed without merging**
