### PR TITLE
feat(tutorial): complete step 5

### PR DESCRIPTION
**Pull request by sergiowebsphere**

### CODE REVIEW

**Comment by lee-chase** [comment]
:cold_sweat: something doesn't look right. Can you post a link to your ibm cloud deployed page.

**Comment by sergiowebsphere** [comment]
Hi lee,

The push was done to my IBM account.
Here is the published link.

https://carbon-tutorial-vue-sgutierr.mybluemix.net/#/

**Comment by lee-chase** [comment]
:thumbsup::100::clap::smile::star:fantastic, you have completed the tutorial and if you have completed all five steps you can now claim the Carbon Developer Essentials Vue badge.  Feel free to stop your running application on IBM Cloud to avoid the possibility of incurring any charges.

**Comment by sergiowebsphere** [comment]
Hello Lee,

Thanks for your review.
I have a question, how should I claim the badge?

Thanks & Regards

**Pull request closed without merging**
