### PR TITLE
feat(tutorial): complete step 5

### PR DESCRIPTION
**Pull request by lsobiech**

### CODE REVIEW

**Comment by lee-chase** [comment]
Your changes look good, can you post a link to your ibm cloud deployment.

**Comment by lsobiech** [comment]
@lee-chase http://carbone-vue-app.mybluemix.net/#/ I attach the link to the master branch where I merged all 5 steps

**Comment by lee-chase** [comment]
:thumbsup::100::clap::smile::star:fantastic, you have completed the tutorial and if you have completed all five steps you can now take a look at the wrapping up step where you will find instructions on claiming the Carbon Developer Essentials Vue badge. Feel free to stop your running application on IBM Cloud to avoid the possibility of incurring any charges.

**Comment by lsobiech** [comment]
> 👍💯👏😄⭐fantastic, you have completed the tutorial and if you have completed all five steps you can now take a look at the wrapping up step where you will find instructions on claiming the Carbon Developer Essentials Vue badge. Feel free to stop your running application on IBM Cloud to avoid the possibility of incurring any charges.

Thank you Lee. It looks like step 3 is not approved yet when I select view from the select list on this website https://badges.carbondesignsystem.com/badges

**Comment by lsobiech** [comment]
@lee-chase https://github.com/carbon-design-system/carbon-tutorial-vue/pull/713 thats the link to the 3rd step, it has to have approved label to be able to submit the form

**Pull request closed without merging**
